#!/bin/bash
set -e 

if [ "$#" -eq 0 ] ; 
then
  echo "Entrypoint did not receive a command."
  echo "Currently accepting only 'serve' as a command"
  exit 1
fi

echo "Entrypoint received command: $1"
if [ "$1" = "serve" ] 
then
  ./serve
else
  echo "Entrypoint received invalid command."
  exit 1
fi